/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

// Config for firebase
export const firebase = {
  apiKey:  process.env.REACT_APP_SECRET_CODE,
  authDomain:  process.env.REACT_APP_authDomain ,
  databaseURL: process.env.REACT_APP_databaseURL ,
  projectId: process.env.REACT_APP_projectId ,
  storageBucket: process.env.REACT_APP_storageBucket ,
  messagingSenderId: process.env.REACT_APP_messagingSenderId ,
  appId: process.env.REACT_APP_appId ,
  measurementId: process.env.REACT_APP_measurementId 
}

// Config to override default reduxFirebase config in store/createStore
// which is not environment specific.
// For more details, visit http://react-redux-firebase.com/docs/api/enhancer.html
export const reduxFirebase = {
  enableLogging: false, // enable/disable Firebase Database Logging
  userProfile: 'users', // where profiles are stored in database
}

export default {
  env,
  firebase,
  reduxFirebase
}
